# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # Install the project in editable mode using pyproject.toml,
  # avoids needing a requirements.txt
  jobs:
    pre_build:
      - pip install -e ".[dev-docs]"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true
