name: Suggestion
description: Suggestions that could improve the repo
title: "[Suggestion]"
labels: ["suggestion"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting new ideas for features and enhancements.
        This issue can be used as a collection of ideas and as a discussion forum.
        Maybe this can encourage people to step up and implement this new feature.
        Please understand that you generally can not expect people to implement this for you.
        Consider discussing this issue with the community and implementing it yourself afterwards.
  - type: textarea
    id: description
    attributes:
      label: "Suggestion"
      description: "A clear and concise description of what you suggest."
    validations:
      required: true
  - type: textarea
    id: problem_related
    attributes:
      label: "Reasons"
      description: "Describe the improvemnts this can bring."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: |
        If you have additional context (screenshots etc.) for this issue, please drop it here.
    validations:
      required: false
