name: Test PyPI release

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main
      uses: actions/checkout@v2
    - name: setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
    - name: build wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: upload to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/*
