name: PyPI Release

on:
  release:
    types: [published]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
    - name: checkout tag
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
    - name: build wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
