name: PyPI Release

on:
  release:
    types: [published]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: checkout tag
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: install build frontend
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build twine
    - name: build distribution
      run: |
        python -m build
    - name: publish distribution on PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
