name: Test PyPI release

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release-test
    permissions:
      id-token: write
    steps:
    - name: checkout main
      uses: actions/checkout@v4
    - name: setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: install build frontend
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build twine
    - name: build distribution
      run: |
        python -m build
    - name: publish distribution on Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
