name: Ruff
on: [push, pull_request]
jobs:
  ruff-lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10.x'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev-docs]"
      - name: Lint with Ruff
        run: ruff --output-format=json-lines . >> $${{ github.workspace }}/lint.json
        # run: ruff --output-format=json-lines . >> $GITHUB_STEP_SUMMARY
        # continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: ruff-lint-report
          path: $${{ github.workspace }}/lint.json
        if: ${{ always() }}
