name: Ruff
on: [push, pull_request]
jobs:
  ruff-lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev-docs]"
      - name: Lint with Ruff
        run: |
          ruff check . --output-format=github .
        continue-on-error: true
