name: Ruff
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-lint:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev-lint-format]"
      - name: Lint with Ruff
        run: ruff --ignore=E722 --output-format=github check .
        continue-on-error: true  # If you want the test to be marked successful regardless
        # run: ruff --output-format=json-lines . >> ${{ github.workspace }}/lint.json  # This saves a json file of the output
      # - name: Upload test report  # If you want to save the json file of the output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ruff-lint-report
      #     path: ${{ github.workspace }}/lint.json
      #   if: ${{ always() }}
